### ISSUE TITLE
Z coordinat in uploaded poligon

### ISSUE THREAD

**Issue by ABiatov** [ABiatov/gbif_shiny_onlineviewer#45]
Приложение падает если загружаемый полигон имеет Z координату.

Добавить проверку на наличие Z координаты и удаление ее, или автоматически все полигоны делать плоскими
 
[Kahovka_Nizhniy_dnepr_3.zip](https://github.com/ABiatov/gbif_shiny_onlineviewer/files/12588740/Kahovka_Nizhniy_dnepr_3.zip)

**Comment by y-yatsiuk** [comment]
Я сделал это в коде загрузки .kml .kmz
Все полигоны автоматически делаются плоскими
