### ISSUE TITLE
таксони

### ISSUE THREAD

**Issue by vasyliukoleksii** [ABiatov/gbif_shiny_onlineviewer#49]
думаю варто додати в таблицю вигрузки таксонинижче царств, до класів,
щоб можна було оперативно птахів наприклад побачити

але можливо додати таксони такі в нову версію вьюера і в сам фільтр. хоча б для хребетних. хоча блін, комахи, молюски - теж питання такого рівню, що людина 99% буде шукати саме комах а не всіх безхребетних
вірніше так: 99% що будуть шукати або клас або всі види одного охоронного списку

**Comment by ABiatov** [comment]
https://github.com/ABiatov/gbif_shiny_onlineviewer/issues/71
